baseURL = ""
languageCode = "en-us"
title = "Bitcoin Conferences"
theme = "yinyang"
buildFuture = true

[params]
  headTitle = "Bitcoin Conferences"
  extraCSSFiles = ["css/custom.css"]

# [[params.socials]]
#   name = "Add"
#   link = "https://github.com"